version: 2
updates:
  # Composer dependencies
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    assignees:
      - "valbeat"
    open-pull-requests-limit: 10
    versioning-strategy: "increase-if-necessary"
    commit-message:
      prefix: "chore"
      include: "scope"