name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: PHP 8.4 Tests
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP 8.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: pcov
          ini-values: pcov.directory=src
          tools: composer:v2
      
      - name: Validate composer.json
        run: composer validate --strict
      
      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-8.4-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-8.4-
      
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      
      - name: Run PHPStan
        run: composer phpstan
      
      - name: Run PHP CS Fixer check
        run: composer cs-check
      
      - name: Run PHPUnit with coverage (PCOV)
        run: |
          vendor/bin/phpunit \
            --coverage-clover build/logs/clover.xml \
            --coverage-html coverage/html \
            --log-junit build/logs/junit.xml \
            --colors=always
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./build/logs/clover.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            build/logs/
            coverage/html/